---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: prodcatalog
  namespace: prodcatalog-ns
spec:
  podSelector:
    matchLabels:
      app: prodcatalog
  listeners:
    - portMapping:
        port: 5000
        protocol: http
      healthCheck:
        protocol: http
        path: '/products/ping'
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  backends:
    - virtualService:
        virtualServiceRef:
          name: proddetail
  serviceDiscovery:
    dns:
      hostname: prodcatalog.prodcatalog-ns.svc.cluster.local
  logging:
    accessLog:
      file:
        path: /dev/stdout
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: prodcatalog
  namespace: prodcatalog-ns
spec:
  awsName: prodcatalog.prodcatalog-ns.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: prodcatalog-router
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  name: prodcatalog-router
  namespace: prodcatalog-ns
spec:
  listeners:
    - portMapping:
        port: 5000
        protocol: http
  routes:
    - name: prodcatalog-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: prodcatalog
              weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodcatalog
  namespace: prodcatalog-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodcatalog
  template:
    metadata:
      labels:
        app: prodcatalog
    spec:
      serviceAccountName: prodcatalog-envoy-proxies
      containers:
        - name: prodcatalog
          image: "${REPOSITORY_URI}"
          imagePullPolicy: Always
          env:
            - name: AGG_APP_URL
              value: "http://proddetail.prodcatalog-ns.svc.cluster.local:3000/catalogDetail"
          livenessProbe:
            httpGet:
              path: /products/ping
              port: 5000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /products/ping
              port: 5000
            successThreshold: 3
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: prodcatalog
  namespace: prodcatalog-ns
  labels:
    app: prodcatalog
spec:
  ports:
    - name: "http"
      port: 5000
      targetPort: 5000
  selector:
    app: prodcatalog